CREATE TABLE cars (
id SERIAL PRIMARY KEY,
brand VARCHAR(50) NOT NULL,
model VARCHAR(50) NOT NULL,
price INTEGER NOT NULL
);

CREATE TABLE men(
id SERIAL PRIMARY KEY,
name VARCHAR(50) NOT NULL,
age INTEGER NOT NULL,
is_driver_license BOOLEAN NOT NULL,
car_id INTEGER NOT NULL REFERENCES cars(id)
);

